from snakemake.utils import min_version

min_version("6.0")


include: "rules/align_asm_to_ref.smk"
include: "rules/mask_hor_arrays.smk"
include: "rules/ident_cen_ctgs.smk"


rule all:
    input:
        rules.ref_align_all.input,
