[settings]
format = "png"
transparent = true
dim = [20.0, 1.5]
axis_h_pad = 0.05
dpi = 300
layout = "tight"
legend_prop = 0.4
legend_pos = "right"

[[tracks]]
position = "relative"
proportion = 0.05
type = "label"
path = "{indir}/cdr.bed"
options = { legend = false, hide_x = true }

[[tracks]]
position = "relative"
proportion = 0.4
type = "label"
path = "{indir}/sat_annot.bed"
options = { legend = true, legend_title = "{chrom}", legend_title_only = true, hide_x = true }

[[tracks]]
position = "overlap"
type = "hor"
path = "{indir}/stv_{typ}.bed"
options = { legend = true, legend_title = "{chrom}", legend_title_only = true, hide_x = true, live_only = false }

[[tracks]]
position = "relative"
proportion = 0.1
type = "horort"
path = "{indir}/stv_{typ}.bed"
options = { legend = false, hide_x = true, scale = 15 }

[[tracks]]
position = "relative"
proportion = 0.1
type = "position"
options = { legend = false, hide_x = false }
