[settings]
title = "{chrom}"
layout = "constrained"
format = ["png", "pdf"]
transparent = false
dim = [16.0, 8.0]
axis_h_pad = 0.05
dpi = 600

[[tracks]]
position = "relative"
type = "label"
proportion = 0.005
path = "{indir}/cdrs.bed"
options = { color = "black", legend = false, hide_x = true }

[[tracks]]
title = "Mean CpG\nmethylation\n(%)"
position = "relative"
type = "bar"
proportion = 0.1
path = "{indir}/methyl.bed"
options = { hide_x = true, ymax = 100.0 }

[[tracks]]
position = "relative"
proportion = 0.05
type = "label"
path = "{indir}/sat_annot.bed"
options = { legend = false, hide_x = true }

[[tracks]]
position = "overlap"
type = "hor"
path = "{indir}/stv.bed"
options = { legend = false, sort_order = "descending", hide_x = true, bg_border = true, hor_filter = 1, live_only = false }

[[tracks]]
position = "relative"
proportion = 0.005
type = "horort"
path = "{indir}/stv.bed"
options = { legend = false, hide_x = true, scale = 15 }

[[tracks]]
position = "relative"
type = "selfident"
proportion = 0.7
path = "{indir}/ident.bed"
options = { legend = true, hide_x = false, invert = true, legend_asp_ratio = 1.0 }

[[tracks]]
position = "relative"
proportion = 0.1
type = "legend"
options = { index = 2, legend_ncols = 10 }
