ref:
  t2t_chm13_v2.0: data/reference/T2T-CHM13v2.fasta
  # Note files are made as part of first steps.
  t2t_chm13_v2.0_cens: results/masked/t2t_chm13_v2.0.hor_arrays_masked.500kbp.fa
  t2t_chm13_v2.0_cens_hardmasked: results/masked/t2t_chm13_v2.0.hor_arrays_masked.fa
tbl: config/table.asm.tbl
aln_threads: 8
mm2_opts: "-x asm5 --secondary=no -s 25000 -K 8G"
second_aln: "no"

## THE FOLLOWING OPTIONS ARE ONLY USED FOR GENE CONVERSION ANALYSIS AND NOT ALIGNMENT AND CAN BE IGNORRED
# subset the gene conversion analysis to just these regions on the reference
#bed: /net/eichler/vol26/projects/chm13_t2t/nobackups/Assembly_analysis/SEDEF/chm13_v1.1_plus38Y.SDs.bed
break_paf: 10000
bed: config/SDs.and.lowid.bed
window: 1000
slide: 100
min_aln_len: 1000000
