chromosomes:
  - "chr1"
  - "chr2"
  - "chr3"
  - "chr4"
  - "chr5"
  - "chr6"
  - "chr7"
  - "chr8"
  - "chr9"
  - "chr10"
  - "chr11"
  - "chr12"
  - "chr13"
  - "chr14"
  - "chr15"
  - "chr16"
  - "chr17"
  - "chr18"
  - "chr19"
  - "chr20"
  - "chr21"
  - "chr22"
  - "chrX"
  - "chrY"

samples:
  - HG002

# Specify container to run workflow if using singularity.
# Optional
container: "docker://logsdonlab/cenmap:latest"

concat_asm:
  input_dir: "data/asm"
  mem: 20GB

ident_cen_ctgs:
  threads_srf: 8
  mem_srf: 50GB
  threads_aln: 8
  mem_aln: 50GB
  bp_merge: 2500000
  bp_slop: 1000000

nucflag:
  input_hifi_reads_fofn_dir: "data/hifi"
  config_nucflag: "config/nucflag.toml"
  threads_aln: 8
  processes_nucflag: 8
  mem_nucflag: 50GB
  mem_aln: 50GB
  samtools_view_flag: 2308
  # asat or live_asat
  ignore_type: "asat"

repeatmasker:
  ref_repeatmasker_output: []
  repeat_colors: "config/repeatmasker_colors.json"
  bp_shannon_window: 5000
  threads: 4

humas_annot:
  mode: "sd" # or "hmmer"
  threads: 6
  mem: 30GB
  hmm_profile: "data/models/AS-HORs-hmmer3.4-071024.hmm.gz"

plot_hor_stv:
  ref_stv: []
  sat_annot_colors: "config/repeatmasker_sat_annot_colors.json"
  stv_annot_colors: "config/stv_annot_colors.tsv"

calculate_hor_length:
  ref_hor_lengths: []

moddotplot:
  mem: 10GB
  ident_thr: 70.0
  window: 5000

ideogram:
  title: "{sm}"
  height: 15
  width: 5

cdr_finder:
  # Either minimap2 or winnowmap
  # Use aligner_opts to override defaults.
  aligner: minimap2
  # aligner_opts: "-y -a --eqx --cs -x lr:hqae -I8g -s 4000" # minimap2
  # aligner_opts: "-y -a --eqx --cs -x map-ont -I8g -s 4000" # winnowmap
  # Expects sample subdir in input_dir.
  # Uses find and file pattern to merge bam.
  input_bam_dir: "data/ont"
  bam_rgx: ".*\\.bam$"
  aln_mem: 50GB
  aln_threads: 8
  window_size: 5000
  alr_threshold: 100000
  bp_alr_merge: 1000
  bp_edge: 500_000
  height_perc_valley_threshold: 0.34
  prom_perc_valley_threshold: 0.3
  extend_edges_std: -1
