name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        lfs: 'true'

    - name: Install Python.
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Snakemake and testing dependencies.
      run: |
        pip install -r <(yq -r '.dependencies[] | select(type == "!!map") | to_entries[].value[]' env_dev.yaml)

    - name: Install Singularity.
      uses: singularityhub/install-singularity@main

    - name: Test scripts.
      run: |
        pytest -vvv

    - name: Test dry-run workflow.
      run: |
        snakemake -c 1 -np \
        --workflow-profile none \
        --configfile test/config/config.yaml

    - name: Test chrY workflow.
      run: |
        snakemake -c 4 -p \
        --workflow-profile none \
        --configfile test/config/config_HG00731.yaml \
        --sdm conda apptainer \
        --show-failed-logs \
        --conda-cleanup-pkgs cache
