name: CI

on: [push, pull_request]

env:
  ENV_DEV: test/env_dev.yaml
  ENV_WRAPPER: env_all.yaml

jobs:
  test_scripts_and_workflow_logic:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        lfs: 'true'
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    - name: Setup Miniforge.
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: dev
    - name: Update environment.
      run:
        conda env update -n dev -f ${{ env.ENV_DEV }}
    - name: Test scripts.
      run: |
        pytest test/ -vvv
    - name: Test can generate Dockerfile.
      run: |
        make dockerfile
    - name: Test dry-run workflow.
      run: |
        snakemake -c 2 -np \
        --workflow-profile none \
        --configfile test/config/config.yaml
    - name: Test primate SF workflow.
      run: |
        snakemake -c 2 -np \
        --workflow-profile none \
        --configfile test/config/config_primates.yaml

  test_workflow_chm13_chrY:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        lfs: 'true'
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    - name: Setup Miniforge.
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: dev
    - name: Update environment.
      run:
        conda env update -n dev -f ${{env.ENV_DEV }}
    - name: Test chrY workflow.
      run: |
        snakemake -c 4 -p \
        --workflow-profile none \
        --configfile test/config/config_HG00731.yaml \
        --sdm conda \
        --show-failed-logs \
        --conda-cleanup-pkgs cache \
        --conda-frontend conda

  test_workflow_mGorGor1_chr16:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        lfs: 'true'
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    - name: Setup Miniforge.
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: dev
    - name: Update environment.
      run:
        conda env update -n dev -f ${{ env.ENV_DEV }}
    - name: Test chrY workflow.
      run: |
        snakemake -c 4 -p \
        --workflow-profile none \
        --configfile test/config/config_mGorGor1.yaml \
        --sdm conda \
        --show-failed-logs \
        --conda-cleanup-pkgs cache \
        --conda-frontend conda

  test_workflow_wrapper:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        lfs: 'true'
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    - name: Setup Miniforge.
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: cenmap
    - name: Update environment.
      run:
        conda env update -n cenmap -f ${{ env.ENV_WRAPPER }}
    - name: Test chrY workflow.
      # TODO: Change to bioconda script later.
      run: |
        ./cenmap \
        -i test/data/assemblies/HG00731/*.fasta.gz \
        --hifi test/data/raw_data/HG00731/*.fastq.gz \
        -s HG00731 \
        -p 4 \
        --chromosomes chrY
