name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        lfs: 'true'

    - name: Install Singularity.
      uses: singularityhub/install-singularity@main

    - name: Install Python.
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Snakemake.
      run: pip install snakemake

    - name: Test dry-run workflow.
      run: |
        snakemake -c 1 -np --configfile test/config/config.yaml

    - name: Test chrY workflow.
      run: |
        snakemake -c 4 -p \
        --configfile test/config/config_HG00731.yaml \
        --use-conda \
        --use-singularity \
        --show-failed-logs \
        --conda-cleanup-pkgs cache

    - name: Test scripts.
      shell: bash -el {0}
      run: |
        pytest -s
