name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Setup env.
      uses: ./.github/workflows/setup_conda.yml
      with:
          env-name: dev
          env-file: test/env_dev.yaml
    - name: Test scripts.
      run: |
        pytest test/ -vvv

    - name: Test can generate Dockerfile.
      run: |
        make dockerfile

    - name: Test dry-run workflow.
      run: |
        snakemake -c 2 -np \
        --workflow-profile none \
        --configfile test/config/config.yaml

    - name: Test primate SF workflow.
      run: |
        snakemake -c 2 -np \
        --workflow-profile none \
        --configfile test/config/config_primates.yaml

  test_workflow_chm13_chrY:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Setup env.
      uses: ./.github/workflows/setup_conda.yml
      with:
          env-name: dev
          env-file: test/env_dev.yaml
    - name: Test chrY workflow.
      run: |
        snakemake -c 4 -p \
        --workflow-profile none \
        --configfile test/config/config_HG00731.yaml \
        --sdm conda \
        --show-failed-logs \
        --conda-cleanup-pkgs cache \
        --conda-frontend conda

  test_workflow_mGorGor1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Setup env.
      uses: ./.github/workflows/setup_conda.yml
      with:
          env-name: dev
          env-file: test/env_dev.yaml
    - name: Test chrY workflow.
      run: |
        snakemake -c 4 -p \
        --workflow-profile none \
        --configfile test/config/config_mGorGor1.yaml \
        --sdm conda \
        --show-failed-logs \
        --conda-cleanup-pkgs cache \
        --conda-frontend conda

  test_wrapper:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Setup env.
      uses: ./.github/workflows/setup_conda.yml
      with:
          env-name: cenmap
          env-file: test/env_all.yaml

    - name: Test chrY workflow.
      # TODO: Change to bioconda script later.
      run: |
        ./cenmap \
        -i test/data/assemblies/HG00731/*.fasta.gz \
        --hifi test/data/raw_data/HG00731/*.fastq.gz \
        -s HG00731 \
        -p 4 \
        --chromosomes chrY
