name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Set up Python.
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Test extract cens, dna-brnn, and nucflag workflow.
      run: |
        snakemake -c 1 -np --configfile test/config/config.yaml

    - name: Test repeatmasker workflow.
      run: |
        snakemake -c 1 -np --configfile test/config/config.yaml -U repeatmasker_only

    - name: Test HumAS-HMMER workflow.
      run: |
        snakemake -c 1 -np --configfile test/config/config.yaml -U humas_hmmer_only

    - name: Test plotting StV workflow.
      run: |
        snakemake -c 1 -np --configfile test/config/config.yaml -U plot_hor_stv_only

    - name: Test scripts.
      run: |
        pytest -s
