name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        lfs: 'true'
    - uses: singularityhub/install-singularity@main
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        channel-priority: true
        activate-environment: test_env
        environment-file: env.yaml

    - name: Test dry-run workflow.
      shell: bash -el {0}
      run: |
        snakemake -c 1 -np --configfile test/config/config.yaml

    - name: Test chrY workflow.
      shell: bash -el {0}
      run: |
        snakemake -c 4 -p \
        --configfile test/config/config_HG00731.yaml \
        --use-conda \
        --use-singularity \
        --show-failed-logs \
        --conda-cleanup-pkgs cache

    - name: Test scripts.
      shell: bash -el {0}
      run: |
        pytest -s
