name: Setup env.

on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
      env-file:
        required: true
        type: string
jobs:
  setup-conda:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        lfs: 'true'

    - name: Setup Miniforge.
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: ${{ inputs.env-name }}

    - name: Get date.
      id: get-date
      run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache conda env.
      uses: actions/cache@v3
      with:
        path: ${{ env.CONDA }}/envs
        key:
          conda-${{ runner.os }}--${{ runner.arch }}--${{
          steps.get-date.outputs.today }}-${{
          hashFiles('${{ inputs.env-file }}') }}-${{ env.CACHE_NUMBER }}
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      id: cache

    - name: Update environment.
      run:
        conda env update -n ${{ inputs.env-name }} -f ${{ inputs.env-file }}
      if: steps.cache.outputs.cache-hit != 'true'
